# Generated by Django 4.0 on 2021-12-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.IntegerField(choices=[(1, 'Exchange'), (2, 'Token')])),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=42)),
                ('abi', models.JSONField()),
                ('start_block', models.IntegerField()),
                ('end_block', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Indexer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexer_id', models.IntegerField()),
                ('start_block', models.IntegerField()),
                ('end_block', models.IntegerField()),
                ('last_block', models.IntegerField()),
                ('step', models.IntegerField()),
                ('target_events_per_request', models.IntegerField(default=1000)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indexer.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_id', models.IntegerField(choices=[(1, 'Mainnet'), (137, 'Polygon')], unique=True)),
                ('explorer_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RangeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_block', models.IntegerField()),
                ('last_block', models.IntegerField()),
                ('step', models.IntegerField()),
                ('count_events', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexer.contract')),
                ('indexer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexer.indexer')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx', models.CharField(max_length=200, unique=True)),
                ('block_number', models.IntegerField()),
                ('block_hash', models.CharField(max_length=200)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_of', to='indexer.account')),
                ('range_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexer.rangeblock')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_of', to='indexer.account')),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_of', to='indexer.contract')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_of', to='indexer.contract')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_of', to='indexer.trade')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indexer.network'),
        ),
    ]
